from decimal import Decimal

CARD_WITHDRAWAL_NET_RATIO = Decimal("0.98") / Decimal("1.02")
CARD_WITHDRAWAL_LOSS_RATIO = Decimal("1") - CARD_WITHDRAWAL_NET_RATIO
CARD_WITHDRAWAL_LOSS_PERCENT = CARD_WITHDRAWAL_LOSS_RATIO * Decimal("100")
