"""upgrade models v2

Revision ID: 17ad7a5dc7e9
Revises: ff44e65dac5b
Create Date: 2026-06-30 12:57:25.884154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17ad7a5dc7e9'
down_revision: Union[str, Sequence[str], None] = 'ff44e65dac5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('top_tank_count', sa.Integer(), nullable=False),
    sa.Column('premium_tank_count', sa.Integer(), nullable=False),
    sa.Column('total_tank_count', sa.Integer(), nullable=False),
    sa.Column('silver_amount', sa.BigInteger(), nullable=False),
    sa.Column('gold_amount', sa.BigInteger(), nullable=False),
    sa.Column('battles_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('win_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_tier_11', sa.Boolean(), nullable=False),
    sa.Column('supplier_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phone_bound', sa.Boolean(), nullable=False),
    sa.Column('is_in_clan', sa.Boolean(), nullable=False),
    sa.Column('tanks_text', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('tanks_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supplier_loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_accounts_game_type'), 'catalog_accounts', ['game_type'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_region'), 'catalog_accounts', ['region'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_sale_price'), 'catalog_accounts', ['sale_price'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_status'), 'catalog_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_supplier_loaded_at'), 'catalog_accounts', ['supplier_loaded_at'], unique=False)
    op.create_table('user_catalog_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('top_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('top_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('premium_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('premium_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('total_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('total_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('silver_amount_min', sa.BigInteger(), nullable=True),
    sa.Column('silver_amount_max', sa.BigInteger(), nullable=True),
    sa.Column('gold_amount_min', sa.BigInteger(), nullable=True),
    sa.Column('gold_amount_max', sa.BigInteger(), nullable=True),
    sa.Column('battles_count_min', sa.Integer(), nullable=True),
    sa.Column('battles_count_max', sa.Integer(), nullable=True),
    sa.Column('wins_count_min', sa.Integer(), nullable=True),
    sa.Column('wins_count_max', sa.Integer(), nullable=True),
    sa.Column('win_rate_percent_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('win_rate_percent_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_tier_11', sa.Boolean(), nullable=True),
    sa.Column('registered_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phone_bound', sa.Boolean(), nullable=True),
    sa.Column('is_in_clan', sa.Boolean(), nullable=True),
    sa.Column('tank_query', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('supplier_loaded_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_loaded_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_field', sa.String(length=32), nullable=False),
    sa.Column('sort_direction', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_type', name='uq_user_catalog_filters_user_game_type')
    )
    op.create_index(op.f('ix_user_catalog_filters_user_id'), 'user_catalog_filters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_catalog_filters_user_id'), table_name='user_catalog_filters')
    op.drop_table('user_catalog_filters')
    op.drop_index(op.f('ix_catalog_accounts_supplier_loaded_at'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_status'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_sale_price'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_region'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_game_type'), table_name='catalog_accounts')
    op.drop_table('catalog_accounts')
    # ### end Alembic commands ###
