"""upgrade models v3

Revision ID: 30a344986da5
Revises: 17ad7a5dc7e9
Create Date: 2026-07-02 14:30:51.373438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a344986da5'
down_revision: Union[str, Sequence[str], None] = '17ad7a5dc7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_entries', sa.Column('question_ru', sa.Text(), nullable=False))
    op.add_column('faq_entries', sa.Column('question_en', sa.Text(), nullable=False))
    op.add_column('faq_entries', sa.Column('answer_ru', sa.Text(), nullable=False))
    op.add_column('faq_entries', sa.Column('answer_en', sa.Text(), nullable=False))
    op.drop_column('faq_entries', 'answer')
    op.drop_column('faq_entries', 'question')
    op.add_column('user_catalog_filters', sa.Column('price_sort_direction', sa.String(length=4), nullable=False))
    op.add_column('user_catalog_filters', sa.Column('last_activity_sort_direction', sa.String(length=4), nullable=False))
    op.add_column('user_catalog_filters', sa.Column('newest_sort_direction', sa.String(length=4), nullable=False))
    op.drop_column('user_catalog_filters', 'sort_direction')
    op.drop_column('user_catalog_filters', 'sort_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_catalog_filters', sa.Column('sort_field', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('user_catalog_filters', sa.Column('sort_direction', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('user_catalog_filters', 'newest_sort_direction')
    op.drop_column('user_catalog_filters', 'last_activity_sort_direction')
    op.drop_column('user_catalog_filters', 'price_sort_direction')
    op.add_column('faq_entries', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('faq_entries', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('faq_entries', 'answer_en')
    op.drop_column('faq_entries', 'answer_ru')
    op.drop_column('faq_entries', 'question_en')
    op.drop_column('faq_entries', 'question_ru')
    # ### end Alembic commands ###
