"""upgrade models v4

Revision ID: 83873b9fe6d8
Revises: 30a344986da5
Create Date: 2026-07-04 10:24:11.665613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83873b9fe6d8'
down_revision: Union[str, Sequence[str], None] = '30a344986da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_catalog_filters', sa.Column('active_sort_field', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_catalog_filters', 'active_sort_field')
    # ### end Alembic commands ###
