"""upgrade models v8

Revision ID: 8cf8f904eb61
Revises: d8a541d595d9
Create Date: 2026-08-13 09:50:55.681948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cf8f904eb61'
down_revision: Union[str, Sequence[str], None] = 'd8a541d595d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    The migration is safe when a missing column was restored manually before
    Alembic could record this revision in ``alembic_version``.
    """
    inspector = sa.inspect(op.get_bind())
    order_columns = {column["name"] for column in inspector.get_columns("orders")}
    transaction_columns = {
        column["name"] for column in inspector.get_columns("transactions")
    }

    if "delivery_data" not in order_columns:
        op.add_column(
            "orders",
            sa.Column("delivery_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        )
    if "checkout_chat_id" not in transaction_columns:
        op.add_column(
            "transactions",
            sa.Column("checkout_chat_id", sa.BigInteger(), nullable=True),
        )
    if "checkout_message_id" not in transaction_columns:
        op.add_column(
            "transactions",
            sa.Column("checkout_message_id", sa.Integer(), nullable=True),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'checkout_message_id')
    op.drop_column('transactions', 'checkout_chat_id')
    op.drop_column('orders', 'delivery_data')
    # ### end Alembic commands ###
