"""upgrade models v7

Revision ID: d8a541d595d9
Revises: e43b9a2da2bb
Create Date: 2026-08-12 11:33:54.183830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8a541d595d9'
down_revision: Union[str, Sequence[str], None] = 'e43b9a2da2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_accounts', sa.Column('reserved_for_user_id', sa.Integer(), nullable=True))
    op.add_column('catalog_accounts', sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('catalog_accounts', 'tanks_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_catalog_accounts_reserved_for_user_id'), 'catalog_accounts', ['reserved_for_user_id'], unique=False)
    op.create_foreign_key(None, 'catalog_accounts', 'users', ['reserved_for_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('catalog_account_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('supplier_item_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('account_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('fulfillment_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'orders', 'catalog_accounts', ['catalog_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('catalog_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('payment_url', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('provider_payment_method', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_transactions_catalog_account_id'), 'transactions', ['catalog_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_transaction_id'), 'transactions', ['provider_transaction_id'], unique=True)
    op.create_foreign_key(None, 'transactions', 'catalog_accounts', ['catalog_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_provider_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_catalog_account_id'), table_name='transactions')
    op.drop_column('transactions', 'failure_reason')
    op.drop_column('transactions', 'provider_payment_method')
    op.drop_column('transactions', 'payment_url')
    op.drop_column('transactions', 'catalog_account_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'fulfillment_payload')
    op.drop_column('orders', 'account_snapshot')
    op.drop_column('orders', 'supplier_item_id')
    op.drop_column('orders', 'catalog_account_id')
    op.drop_constraint(None, 'catalog_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_accounts_reserved_for_user_id'), table_name='catalog_accounts')
    op.alter_column('catalog_accounts', 'tanks_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('catalog_accounts', 'reserved_at')
    op.drop_column('catalog_accounts', 'reserved_for_user_id')
    # ### end Alembic commands ###
