"""upgrade models v6

Revision ID: e43b9a2da2bb
Revises: dcefe8cee724
Create Date: 2026-07-04 14:23:04.072554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43b9a2da2bb'
down_revision: Union[str, Sequence[str], None] = 'dcefe8cee724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_accounts', sa.Column('supplier_item_id', sa.BigInteger(), nullable=False))
    op.add_column('catalog_accounts', sa.Column('supplier_category_slug', sa.String(length=64), nullable=False))
    op.add_column('catalog_accounts', sa.Column('supplier_item_state', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_catalog_accounts_supplier_category_slug'), 'catalog_accounts', ['supplier_category_slug'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_supplier_item_id'), 'catalog_accounts', ['supplier_item_id'], unique=True)
    op.create_index(op.f('ix_catalog_accounts_supplier_item_state'), 'catalog_accounts', ['supplier_item_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_accounts_supplier_item_state'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_supplier_item_id'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_supplier_category_slug'), table_name='catalog_accounts')
    op.drop_column('catalog_accounts', 'supplier_item_state')
    op.drop_column('catalog_accounts', 'supplier_category_slug')
    op.drop_column('catalog_accounts', 'supplier_item_id')
    # ### end Alembic commands ###
