"""initial schema

Revision ID: f94dde1b651e
Revises: 
Create Date: 2026-08-18 12:58:11.391173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94dde1b651e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_enabled', sa.Boolean(), nullable=False),
    sa.Column('mir_tankov_sales_enabled', sa.Boolean(), nullable=False),
    sa.Column('tanks_blitz_sales_enabled', sa.Boolean(), nullable=False),
    sa.Column('world_of_tanks_sales_enabled', sa.Boolean(), nullable=False),
    sa.Column('wot_blitz_sales_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_ru', sa.Text(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('answer_ru', sa.Text(), nullable=False),
    sa.Column('answer_en', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_sort_order'), 'faq_entries', ['sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('catalog_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_item_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_category_slug', sa.String(length=64), nullable=False),
    sa.Column('supplier_item_state', sa.String(length=32), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reserved_for_user_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('top_tank_count', sa.Integer(), nullable=False),
    sa.Column('premium_tank_count', sa.Integer(), nullable=False),
    sa.Column('total_tank_count', sa.Integer(), nullable=False),
    sa.Column('silver_amount', sa.BigInteger(), nullable=False),
    sa.Column('gold_amount', sa.BigInteger(), nullable=False),
    sa.Column('battles_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('win_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_tier_11', sa.Boolean(), nullable=False),
    sa.Column('supplier_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phone_bound', sa.Boolean(), nullable=False),
    sa.Column('is_in_clan', sa.Boolean(), nullable=False),
    sa.Column('tanks_text', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('tanks_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supplier_loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reserved_for_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_accounts_game_type'), 'catalog_accounts', ['game_type'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_region'), 'catalog_accounts', ['region'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_reserved_for_user_id'), 'catalog_accounts', ['reserved_for_user_id'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_sale_price'), 'catalog_accounts', ['sale_price'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_status'), 'catalog_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_supplier_category_slug'), 'catalog_accounts', ['supplier_category_slug'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_supplier_item_id'), 'catalog_accounts', ['supplier_item_id'], unique=True)
    op.create_index(op.f('ix_catalog_accounts_supplier_item_state'), 'catalog_accounts', ['supplier_item_state'], unique=False)
    op.create_index(op.f('ix_catalog_accounts_supplier_loaded_at'), 'catalog_accounts', ['supplier_loaded_at'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_code', name='uq_favorites_user_product_code')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderated_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('user_catalog_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('top_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('top_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('premium_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('premium_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('total_tank_count_min', sa.Integer(), nullable=True),
    sa.Column('total_tank_count_max', sa.Integer(), nullable=True),
    sa.Column('silver_amount_min', sa.BigInteger(), nullable=True),
    sa.Column('silver_amount_max', sa.BigInteger(), nullable=True),
    sa.Column('gold_amount_min', sa.BigInteger(), nullable=True),
    sa.Column('gold_amount_max', sa.BigInteger(), nullable=True),
    sa.Column('battles_count_min', sa.Integer(), nullable=True),
    sa.Column('battles_count_max', sa.Integer(), nullable=True),
    sa.Column('wins_count_min', sa.Integer(), nullable=True),
    sa.Column('wins_count_max', sa.Integer(), nullable=True),
    sa.Column('win_rate_percent_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('win_rate_percent_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_tier_11', sa.Boolean(), nullable=True),
    sa.Column('registered_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phone_bound', sa.Boolean(), nullable=True),
    sa.Column('is_in_clan', sa.Boolean(), nullable=True),
    sa.Column('tank_query', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('supplier_loaded_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_loaded_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_sort_field', sa.String(length=32), nullable=False),
    sa.Column('price_sort_direction', sa.String(length=4), nullable=False),
    sa.Column('last_activity_sort_direction', sa.String(length=4), nullable=False),
    sa.Column('newest_sort_direction', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_type', name='uq_user_catalog_filters_user_game_type')
    )
    op.create_index(op.f('ix_user_catalog_filters_user_id'), 'user_catalog_filters', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_account_id', sa.Integer(), nullable=True),
    sa.Column('supplier_item_id', sa.BigInteger(), nullable=True),
    sa.Column('account_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fulfillment_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sale_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_account_id'], ['catalog_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('catalog_account_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=64), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('provider_payment_method', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('checkout_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('checkout_message_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_account_id'], ['catalog_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_catalog_account_id'), 'transactions', ['catalog_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_transaction_id'), 'transactions', ['provider_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_provider_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_catalog_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('orders')
    op.drop_index(op.f('ix_user_catalog_filters_user_id'), table_name='user_catalog_filters')
    op.drop_table('user_catalog_filters')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_catalog_accounts_supplier_loaded_at'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_supplier_item_state'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_supplier_item_id'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_supplier_category_slug'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_status'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_sale_price'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_reserved_for_user_id'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_region'), table_name='catalog_accounts')
    op.drop_index(op.f('ix_catalog_accounts_game_type'), table_name='catalog_accounts')
    op.drop_table('catalog_accounts')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_faq_entries_sort_order'), table_name='faq_entries')
    op.drop_table('faq_entries')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
