"""upgrade models

Revision ID: ff44e65dac5b
Revises: fa0a277a5838
Create Date: 2026-06-29 20:34:07.954133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff44e65dac5b'
down_revision: Union[str, Sequence[str], None] = 'fa0a277a5838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sale_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('supplier_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('payout_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('orders', 'payout_fee_percent')
    op.drop_column('orders', 'supplier_amount')
    op.drop_column('orders', 'sale_amount')
    # ### end Alembic commands ###
